name: manage-azure-policy-a92d207d
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'Tags/Standard_tags_should_be_applied/policies/Audit_resource_groups_missting_tag:_businessowner_21fcd78f-845c-4c02-b1b9-a0e796a7d19e/**'
#      - 'Tags/Standard_tags_should_be_applied/policies/Audit_resource_groups_missing_tag:_compositeApp_21fcd78f-845c-4c02-b1b9-a0e796a7d1a5/**'
#      - 'Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_compositeApp_21fcd78f-845c-4c02-b1b9-a0e796a7d1ad/**'
#      - 'Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_businessowner_21fcd78f-845c-4c02-b1b9-a0e796a7da52/**'
#      - 'Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_costCode_21fcd78f-845c-4c02-b1b9-a0e796a7da59/**'
#      - 'Tags/Standard_tags_should_be_applied/policies/Deny_resource_groups_missing_tag:_costCode_a6ff33bc-c827-4193-a3e7-b7ae413538f9/**'
#      - .github/workflows/manage-azure-policy-a92d207d.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_a92d207d}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          Tags/Standard_tags_should_be_applied/policies/Audit_resource_groups_missting_tag:_businessowner_21fcd78f-845c-4c02-b1b9-a0e796a7d19e/**
          Tags/Standard_tags_should_be_applied/policies/Audit_resource_groups_missing_tag:_compositeApp_21fcd78f-845c-4c02-b1b9-a0e796a7d1a5/**
          Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_compositeApp_21fcd78f-845c-4c02-b1b9-a0e796a7d1ad/**
          Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_businessowner_21fcd78f-845c-4c02-b1b9-a0e796a7da52/**
          Tags/Standard_tags_should_be_applied/policies/Inherit_RG_tag_to_resource:_costCode_21fcd78f-845c-4c02-b1b9-a0e796a7da59/**
          Tags/Standard_tags_should_be_applied/policies/Deny_resource_groups_missing_tag:_costCode_a6ff33bc-c827-4193-a3e7-b7ae413538f9/**
